using Content.Client.Lobby.UI;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;


namespace Content.Client._Floof.LoadoutsAndTraits.Loadouts;


[GenerateTypedNameReferences]
public sealed partial class LoadoutExtendedInfo : BoxContainer
{
    public LoadoutSelector2 Owner;
    public LoadoutPreference Preference => Owner.Preference;
    public LoadoutPrototype Prototype => Owner.Prototype;

    public event Action? OnPreferencesChanged;

    public LoadoutExtendedInfo(LoadoutSelector2 owner)
    {
        RobustXamlLoader.Load(this);
        Owner = owner;

        SaveButton.OnPressed += _ => Save();
        NameEdit.OnTextChanged += _ =>
            Preference.CustomName = string.IsNullOrEmpty(NameEdit.Text) ? null : NameEdit.Text;
        DescriptionEdit.OnTextChanged += _ =>
            Preference.CustomDescription = string.IsNullOrEmpty(Rope.Collapse(DescriptionEdit.TextRope)) ? null : Rope.Collapse(DescriptionEdit.TextRope);
        SpecialColorTintToggle.OnToggled += args =>
            UpdateState(false);
        ColorEdit.OnColorChanged += _ =>
        {
            Preference.CustomColorTint = GetColorTint()?.ToHex();
            Owner.UpdatePaint();
        };

        UpdateState();
    }

    public void Save()
    {
        Preference.CustomColorTint = GetColorTint()?.ToHex();
        Preference.Selected = Owner.PreferenceButton.Pressed;
        UpdateState();
    }

    /// <summary>
    ///     Updates the UI state.
    /// </summary>
    /// <param name="fetchPreferenceData">Whether the states of toggle buttons and fields should be fetched from the parent on this invocation.</param>
    public void UpdateState(bool fetchPreferenceData = true)
    {
        if (fetchPreferenceData)
        {
            NameEdit.Text = Owner.Preference.CustomName ?? "";
            DescriptionEdit.TextRope = new Rope.Leaf(Owner.Preference.CustomDescription ?? "");
            SpecialColorTintToggle.Pressed = Owner.Preference.CustomColorTint != null;
            ColorEdit.Color = Color.FromHex(Owner.Preference.CustomColorTint, Color.White);
        }

        SpecialName.Visible = Owner.Loadout.CustomName;
        SpecialDescription.Visible = Owner.Loadout.CustomDescription;
        SpecialColorTintToggle.Visible = Owner.Loadout.CustomColorTint;
        ColorEdit.Visible = Owner.Loadout.CustomColorTint && SpecialColorTintToggle.Pressed;

        // ...future me problem. call me when wizden decides to randomly remove TryGetString but yet keep GetString.
        #pragma warning disable CS0618 // Type or member is obsolete

        NameEdit.PlaceHolder = Owner.Owner.GetLocalizedName(Prototype);
        DescriptionEdit.Placeholder = new Rope.Leaf(Owner.Owner.GetLocalizedDescription(Prototype));

        #pragma warning restore CS0618 // Type or member is obsolete
    }

    public Color? GetColorTint() => SpecialColorTintToggle.Pressed ? ColorEdit.Color : null;
}

