using System.Linq;
using System.Numerics;
using Content.Client.Administration.UI;
using Content.Shared._Floof.LoadoutsAndTraits.Prototypes;
using Prometheus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;


namespace Content.Client._Floof.LoadoutsAndTraits;

/// <summary>
///     Represents an abstract page of loadout customization menu that uses a tree-like structure and keeps track of character "points".
///
///     This class wraps <see cref="AbstractLoadoutTreeUiModel"/> because RT doesn't support abstract generic classes in the ui.
/// </summary>
public abstract partial class AbstractLoadoutTreeCharacterPage<TProto, TCategory, TSelector> : Control
    where TProto : class, IRecursivePrototype<TCategory, TProto>, IPrototype
    where TCategory : class, IRecursivePrototypeCategory<TCategory, TProto>, IPrototype
    where TSelector : Control
{
    [Dependency] protected readonly IPrototypeManager ProtoMan = default!;

    /// <summary>
    ///     List of all prototypes relevant to this page.
    /// </summary>
    protected List<TProto> AllPrototypes = new();
    protected List<TCategory> AllCategories = new();
    protected readonly List<CategoryTreeItem> RootCategories = new();
    protected bool PrototypesLoaded;
    protected readonly ISawmill Log = Logger.GetSawmill($"tree-page-{typeof(TProto)}");

    protected bool LayoutInitialized = false;
    protected bool ShowUnusable = false;
    /// <summary>
    ///     Prototype currently being shown in the details container.
    ///     Null if no prototype is being shown.
    /// </summary>
    protected TProto? ShowingDetailsFor;
    /// <summary>
    ///     Current path of categories. Empty if the user is in the "root root" category, having not yet selected anything.
    /// </summary>
    protected readonly Stack<CategoryTreeItem> CurrentPath = new();

    /// <summary>
    ///     List of all point counters relevant to this page. This includes trait points, trait slots, etc.
    ///     Should be initialized in the constructor.
    /// </summary>
    protected readonly List<PointCounterDef> Counters = new();
    public bool CountersValid { get; private set; }

    /// <summary>
    ///     Actual UI wrapped by this model.
    /// </summary>
    public AbstractLoadoutTreeUiModel Model { get; }

    protected AbstractLoadoutTreeCharacterPage()
    {
        Model = new();
        IoCManager.InjectDependencies(this);

        Dictionary<Button, ConfirmationData> confirmationData = new();
        Model.ShowUnusableButton.OnToggled += args =>
        {
            ShowUnusable = args.Pressed;
            UpdateChoices();
        };
        Model.RemoveUnusableButton.OnPressed += (args) =>
        {
            if (!AdminUIHelpers.TryConfirm(Model.RemoveUnusableButton, confirmationData))
                return;

            RemoveUnusable();
        };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        ProtoMan.PrototypesReloaded += UpdatePrototypes;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        ProtoMan.PrototypesReloaded -= UpdatePrototypes;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (Visible)
        {
            if (!PrototypesLoaded)
                UpdatePrototypes(null);

            if (!LayoutInitialized)
            {
                InitializeLayout();
                LayoutInitialized = true;
            }
        }

        base.FrameUpdate(args);
    }

    /// <summary>
    ///     Called when prototypes are reloaded and when first shown in the UI.
    ///     Inheritors must call the supermethod or set PrototypesLoaded to true inside it.
    /// </summary>
    protected virtual void UpdatePrototypes(PrototypesReloadedEventArgs? args)
    {
        if (args != null && !args.WasModified<TProto>() && !args.WasModified<TCategory>())
            return;

        AllPrototypes = ProtoMan.EnumeratePrototypes<TProto>().ToList();
        AllCategories = ProtoMan.EnumeratePrototypes<TCategory>().ToList();

        RootCategories.Clear();
        BuildTree(AllCategories.Where(it => it.Root).ToList(), RootCategories);
        PrototypesLoaded = true;

        #if DEBUG
        // Ensure all prototypes are in a category
        foreach (var prototype in AllPrototypes)
        {
            if (AllCategories.None(it => it.SubCategories.Contains(prototype.ID)))
            {
                Log.Error($"Prototype {prototype.ID} is not in any valid category.");
            }
        }
        #endif
    }

    /// <summary>
    ///     Recursively builds the tree of prototypes, outputting the result into <paramref name="outputList"/>.
    /// </summary>
    protected virtual void BuildTree(List<TCategory> rootCategories, List<CategoryTreeItem> outputList)
    {
        foreach (var category in rootCategories)
        {
            CategoryTreeItem categoryTreeItem;

            var locName = GetLocalizedName(category);
            if (category.SubCategories.Count == 0)
            {
                // Terminal node
                categoryTreeItem = new(
                    category,
                    locName,
                    AllPrototypes.Where(it => it.Category == category.ID).ToList(),
                    null);
                outputList.Add(categoryTreeItem);

                if (category.SubCategories.Count > 0)
                    Log.Error($"Category {locName} contains both terminal and non-terminal nodes. Skipping non-terminals.");

                return;
            }

            // Non-terminal node
            var subCatsList = new List<CategoryTreeItem>();
            var subcategories = new List<TCategory>();
            foreach (var subCatId in category.SubCategories)
            {
                // Technically the yaml linter should catch that, but...
                if (!ProtoMan.TryIndex(subCatId, out var subCatProto))
                {
                    Log.Error($"Category {locName} references an unknown subcategory {subCatId}");
                    continue;
                }

                subcategories.Add(subCatProto);
            }

            BuildTree(subcategories, subCatsList);
            categoryTreeItem = new(
                category,
                locName,
                null,
                subCatsList);

            outputList.Add(categoryTreeItem);
        }
    }

    /// <summary>
    ///     Initializes the layout of the page. This is called when the page is first shown.
    /// </summary>
    protected virtual void InitializeLayout()
    {
        foreach (var counter in Counters)
        {
            PointCounterControl pointCounterControl = new(counter.locString);
            Model.PointCountersContainer.AddChild(pointCounterControl);
            counter.Control = pointCounterControl;
        }

        UpdatePath();
        UpdateTabs();
        UpdateChoices();
        UpdateDetails();
    }

    protected virtual void UpdateCounters()
    {
        foreach (var counter in Counters)
        {
            if (counter.Control is null)
                continue;

            var maxPoints = counter.GetMaxPoints();
            var currentPoints = counter.CurrentPoints;
            counter.Control.SetMax(maxPoints);
            counter.Control.SetValue(currentPoints);
        }
    }

    /// <summary>
    ///     Updates the category path panel.
    /// </summary>
    protected virtual void UpdatePath()
    {
        if (CurrentPath.Count == 0)
        {
            Model.PathContainer.AddChild(new Label() { Text = "@Root" });
            return;
        }

        var oldPath = Model.PathContainer.Children.Where(it => it is PathControl).Cast<PathControl>().ToArray();
        var newPath = CurrentPath.ToArray();

        // See if any first entries can be saved, dispose of the rest
        var commonLength = Math.Min(oldPath.Length, newPath.Length);
        var saved = 0;
        int i;
        for (i = 0; i < commonLength; i++)
        {
            if (oldPath[i].Category.ID != newPath[i].Category.ID)
                break;

            saved++;
        }

        Model.PathContainer.RemoveAllChildren();
        for (i = 0; i < newPath.Length; i++)
        {
            // Add a separator first
            if (i > saved)
                Model.PathContainer.AddChild(new Label());

            var item = i < saved ? oldPath[i] : null;
            if (item == null)
            {
                item = new(newPath[i].Category, GetLocalizedName(newPath[i].Category), i);
                item.GoButton.OnPressed += _ => GoBackTo(item.Depth);
            }
            Model.PathContainer.AddChild(item);
        }
    }

    protected virtual void UpdateTabs()
    {
        Model.TabContainer.RemoveAllChildren();

        List<CategoryTreeItem>? categories;
        if (CurrentPath.Count == 0)
            categories = RootCategories;
        else
            categories = CurrentPath.Peek().Subcategories;

        if (categories == null)
            return;

        foreach (var category in categories)
        {
            var categoryButton = new CategoryButton(category, GetLocalizedName(category.Category));
            categoryButton.OnPressed += _ => GoIntoCategory(category);
            Model.TabContainer.AddChild(categoryButton);
        }
    }

    protected virtual void UpdateChoices()
    {
        Model.ChoicesContainer.RemoveAllChildren();

        var currentCategory = CurrentPath.Count > 0
            ? CurrentPath.Peek().Prototypes
            : null;

        if (currentCategory == null)
        {
            Model.ChoicesContainer.AddChild(new Label()
            {
                Text = "This category contains no items." // TODO localize
            });
            return;
        }

        foreach (var prototype in currentCategory)
        {
            if (!ShowUnusable && !IsUsable(prototype, out var reasons))
                continue;

            var selector = CreateSelector(prototype);
            Model.ChoicesContainer.AddChild(selector);
        }

        if (Model.ChoicesContainer.ChildCount == 0)
        {
            Model.ChoicesContainer.AddChild(new Label()
            {
                Text = "No items match the requirements." // TODO localize
            });
        }
    }

    protected virtual void UpdateDetails()
    {
        if (ShowingDetailsFor == null)
        {
            Model.DetailsContainer.Visible = false;
            return;
        }

        Model.DetailsContainer.Visible = true;
        Model.DetailsContainer.RemoveAllChildren();
        UpdateExtendedPanel();
    }

    protected virtual void RemoveUnusable()
    {
        var unset = 0;
        foreach (var prototype in AllPrototypes)
        {
            if (!IsSelected(prototype) || IsUsable(prototype, out var reasons))
                continue;

            SetSelected(prototype, false);
            unset++;
        }

        Log.Info($"Deselected {unset} items.");
    }

    /// <summary>
    ///     Should be called by inheritors when/if the user wants to expand the given item.
    /// </summary>
    public void Expand(TProto? prototype)
    {
        ShowingDetailsFor = prototype;
        UpdateDetails();
    }

    /// <summary>
    ///     Appends a category to the current path. Does not validate the path for validity.
    /// </summary>
    /// <param name="category"></param>
    public void GoIntoCategory(CategoryTreeItem category)
    {
        ShowingDetailsFor = null;
        CurrentPath.Push(category);
        UpdatePath();
        UpdateTabs();
        UpdateChoices();
        UpdateDetails();
    }

    /// <summary>
    ///     Returns to the given category depth in the path. If depth is 0, returns to the root.
    /// </summary>
    public void GoBackTo(int depth)
    {
        ShowingDetailsFor = null;
        while (CurrentPath.Count > depth)
            CurrentPath.Pop();

        UpdatePath();
        UpdateTabs();
        UpdateChoices();
        UpdateDetails();
    }

    public abstract TSelector CreateSelector(TProto prototype);

    /// <summary>
    ///     Called when the user tries to view the extended detail/settings of a prototype.
    ///     Should update DetailsContainer (note that it will usually be cleared - though not disposed of - before calling this).
    /// </summary>
    protected abstract void UpdateExtendedPanel();

    /// <summary>
    ///     Checks if the player can use the provided loadout, regardless of points.
    /// </summary>
    public abstract bool IsUsable(TProto prototype, out List<string> reasons);

    public abstract bool IsSelected(TProto prototype);

    public abstract void SetSelected(TProto prototype, bool selected);

    public abstract string GetLocalizedName(TCategory prototype);

    public abstract string GetLocalizedName(TProto prototype);

    public record class PointCounterDef(string locString, Func<TProto, int> GetPrototypePoints, Func<int> GetMaxPoints)
    {
        public int CurrentPoints { get; internal set; } = int.MinValue;
        public int MaxPoints { get; internal set; } = int.MinValue;

        internal PointCounterControl? Control;
    }

    /// <summary>
    ///     An item of the prototype tree. It can either be terminal and contain prototypes, or be non-terminal and contain subcategories.
    ///     It cannot be both.
    /// </summary>
    public record class CategoryTreeItem(TCategory Category, string LocalizedName, List<TProto>? Prototypes, List<CategoryTreeItem>? Subcategories)
    {
        public bool Terminal => Prototypes != null;
        public bool NonTerminal => Subcategories != null;

        public void Validate()
        {
            if (Terminal && NonTerminal || !Terminal && !NonTerminal)
                throw new InvalidOperationException($"Prototype {typeof(TCategory).Name} {Category.ID} must contain either prototypes or subcategories, but not both.");
        }
    }

    public sealed class PathControl : BoxContainer
    {
        public TCategory Category { get; }
        public string LocalizedName { get; }
        public int Depth { get; }
        public bool IsCurrent { get => !GoButton.Disabled; set => GoButton.Disabled = value; }

        public readonly Label Text;
        public readonly TextureButton GoButton;

        public PathControl(TCategory category, string localizedName, int depth)
        {
            Category = category;
            LocalizedName = localizedName;
            Depth = depth;

            HorizontalAlignment = HAlignment.Stretch;

            Text = new()
            {
                Text = localizedName,
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Margin = new(2)
            };
            GoButton = new()
            {
                TexturePath = "/Textures/Interface/eject.png",
                SetSize = new(48)
            };
            AddChild(Text);
            AddChild(GoButton);
        }
    }

    public sealed class CategoryButton : Button
    {
        public CategoryTreeItem Category { get; }
        public string LocalizedName { get; }

        public CategoryButton(CategoryTreeItem category, string localizedName)
        {
            Category = category;
            LocalizedName = localizedName;

            Text = localizedName;
            StyleClasses.Add("OpenBoth");
        }
    }
}
