using System.Linq;
using System.Numerics;
using Content.Client.Administration.UI;
using Content.Shared._Floof.LoadoutsAndTraits.Prototypes;
using Prometheus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;


namespace Content.Client._Floof.LoadoutsAndTraits;

// TODO implement point calculation (curerntly a stub)
// fix texture rects and sprite views being misplaced
// implement

/// <summary>
///     Represents an abstract page of loadout customization menu that uses a tree-like structure and keeps track of character "points".
///
///     This class wraps <see cref="AbstractLoadoutTreeUiModel"/> because RT doesn't support abstract generic classes in the ui.
/// </summary>
public abstract partial class AbstractLoadoutTreeCharacterPage<TProto, TCategory, TSelector> : Control
    where TProto : class, IRecursivePrototype<TCategory, TProto>, IPrototype
    where TCategory : class, IRecursivePrototypeCategory<TCategory, TProto>, IPrototype
    where TSelector : Control
{
    [Dependency] protected readonly IPrototypeManager ProtoMan = default!;

    /// <summary>
    ///     List of all prototypes relevant to this page.
    /// </summary>
    protected List<TProto> AllPrototypes = new();
    protected List<TCategory> AllCategories = new();
    protected readonly List<CategoryTreeItem> RootCategories = new();
    protected bool PrototypesLoaded;
    protected readonly ISawmill Log = Logger.GetSawmill($"tree-page-{typeof(TProto)}");

    protected bool LayoutInitialized = false;
    protected bool ShowUnusable = false;
    /// <summary>
    ///     Prototype currently being shown in the details container.
    ///     Null if no prototype is being shown.
    /// </summary>
    protected TProto? ShowingDetailsFor;
    /// <summary>
    ///     Current path of categories. Root category is represented by a "root" entry.
    /// </summary>
    protected readonly Stack<CategoryTreeItem> CurrentPath = new();
    /// <summary>
    ///     Pseudo-category that represents the root of the tree.
    /// </summary>
    protected CategoryTreeItem RootCategory { get; private set; } = new(null, "root", null, null);

    /// <summary>
    ///     List of all point counters relevant to this page. This includes trait points, trait slots, etc.
    ///     Should be initialized in the constructor.
    /// </summary>
    protected readonly List<PointCounterDef> Counters = new();
    public bool CountersValid { get; private set; }

    /// <summary>
    ///     Actual UI wrapped by this model.
    /// </summary>
    public AbstractLoadoutTreeUiModel Model { get; }

    protected AbstractLoadoutTreeCharacterPage()
    {
        IoCManager.InjectDependencies(this);
        Model = new();
        AddChild(Model);

        Dictionary<Button, ConfirmationData> confirmationData = new();
        Model.ShowUnusableButton.OnToggled += args =>
        {
            ShowUnusable = args.Pressed;
            UpdateChoices();
        };
        Model.RemoveUnusableButton.OnPressed += (args) =>
        {
            if (!AdminUIHelpers.TryConfirm(Model.RemoveUnusableButton, confirmationData))
                return;

            RemoveUnusable();
        };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        ProtoMan.PrototypesReloaded += UpdatePrototypes;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        ProtoMan.PrototypesReloaded -= UpdatePrototypes;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (Visible)
        {
            if (!PrototypesLoaded)
                UpdatePrototypes(null);

            if (!LayoutInitialized)
            {
                InitializeLayout();
                LayoutInitialized = true;
            }
        }

        base.FrameUpdate(args);
    }

    /// <summary>
    ///     Called when prototypes are reloaded and when first shown in the UI.
    ///     Inheritors must call the supermethod or set PrototypesLoaded to true inside it.
    /// </summary>
    protected virtual void UpdatePrototypes(PrototypesReloadedEventArgs? args)
    {
        if (args != null && !args.WasModified<TProto>() && !args.WasModified<TCategory>())
            return;

        AllPrototypes = ProtoMan.EnumeratePrototypes<TProto>().ToList();
        AllCategories = ProtoMan.EnumeratePrototypes<TCategory>().ToList();

        RootCategories.Clear();
        BuildTree(AllCategories.Where(it => it.Root).ToList(), RootCategories);
        PrototypesLoaded = true;

        RootCategory = new(null, "root", null, RootCategories);

        #if DEBUG
        // Ensure all prototypes are in a category
        foreach (var prototype in AllPrototypes)
        {
            if (AllCategories.None(it => it.SubCategories.Contains(prototype.ID)))
            {
                Log.Error($"Prototype {prototype.ID} is not in any valid category.");
            }
        }
        #endif
    }

    /// <summary>
    ///     Recursively builds the tree of prototypes, outputting the result into <paramref name="outputList"/>.
    /// </summary>
    protected virtual void BuildTree(List<TCategory> rootCategories, List<CategoryTreeItem> outputList)
    {
        foreach (var category in rootCategories)
        {
            CategoryTreeItem categoryTreeItem;

            var locName = GetLocalizedName(category);
            if (category.SubCategories.Count == 0)
            {
                // Terminal node
                categoryTreeItem = new(
                    category,
                    locName,
                    AllPrototypes.Where(it => it.Category == category.ID).ToList(),
                    null);
                outputList.Add(categoryTreeItem);

                if (category.SubCategories.Count > 0)
                    Log.Error($"Category {locName} contains both terminal and non-terminal nodes. Skipping non-terminals.");

                continue;
            }

            // Non-terminal node
            var subcategories = new List<TCategory>();
            foreach (var subCatId in category.SubCategories)
            {
                // Technically the yaml linter should catch that, but...
                if (!ProtoMan.TryIndex(subCatId, out var subCatProto))
                {
                    Log.Error($"Category {locName} references an unknown subcategory {subCatId}");
                    continue;
                }

                subcategories.Add(subCatProto);
            }

            var subCatsList = new List<CategoryTreeItem>();
            BuildTree(subcategories, subCatsList);
            categoryTreeItem = new(
                category,
                locName,
                null,
                subCatsList);

            outputList.Add(categoryTreeItem);
        }
    }

    /// <summary>
    ///     Initializes the layout of the page. This is called when the page is first shown.
    /// </summary>
    protected virtual void InitializeLayout()
    {
        foreach (var counter in Counters)
        {
            PointCounterControl pointCounterControl = new(counter.locString);
            Model.PointCountersContainer.AddChild(pointCounterControl);
            counter.Control = pointCounterControl;
        }

        UpdatePath();
        UpdateCategories();
        UpdateChoices();
        UpdateDetails();
        UpdateCounters();
    }

    protected virtual void UpdateCounters()
    {
        var valid = true;
        foreach (var counter in Counters)
        {
            valid = valid && counter.Valid; // Using && instead of &= for short-circuiting
            if (counter.Control is null)
                continue;

            var maxPoints = counter.GetMaxPoints();
            var currentPoints = counter.CurrentPoints;
            counter.Control.SetMax(maxPoints);
            counter.Control.SetValue(currentPoints);
        }
    }

    /// <summary>
    ///     Updates the category path panel.
    /// </summary>
    protected virtual void UpdatePath()
    {
        EnsurePathIsRooted();

        var oldPath = Model.PathContainer.Children.Where(it => it is PathButton).Cast<PathButton>().ToArray();
        var newPath = CurrentPath.ToArray();
        // NOTE: since CurrentPath is a stack, newPath is in reverse order. The root category is at the end of the array.
        CategoryTreeItem getNew(int index) => newPath[newPath.Length - index - 1];

        // See if any first entries can be saved, dispose of the rest
        var commonLength = Math.Min(oldPath.Length, newPath.Length);
        var saved = 0;
        int i;
        for (i = 0; i < commonLength; i++)
        {
            if (oldPath[i].Category?.ID != getNew(i).Prototype?.ID)
                break;

            saved++;
        }

        Model.PathContainer.RemoveAllChildren();
        for (i = 0; i < newPath.Length; i++)
        {
            var item = i < saved ? oldPath[i] : null;
            if (item == null)
            {
                var cat = getNew(i).Prototype;
                item = new(cat, cat == null ? string.Empty : GetLocalizedName(cat), i);
                item.OnPressed += _ => GoBackTo(item.Depth);
            }
            Model.PathContainer.AddChild(item);
        }
    }

    private void EnsurePathIsRooted()
    {
        // Is there a more sane way to do this? Ideally we shouldn't keep that pseudo-category there, but it simplifies the code.
        if (CurrentPath.Count == 0)
            CurrentPath.Push(RootCategory);

        DebugTools.Assert(CurrentPath.FirstOrDefault() == RootCategory, "Path is not rooted");
        DebugTools.Assert(CurrentPath.Count(it => it == RootCategory) == 1, "Path contains bogus roots");
    }

    protected virtual void UpdateCategories()
    {
        Model.TabContainer.RemoveAllChildren();

        List<CategoryTreeItem>? categories;
        categories = CurrentPath.Count == 0 ? RootCategories : CurrentPath.Peek().Subcategories;

        if (categories == null)
            return;

        foreach (var category in categories)
        {
            if (category.Prototype is null)
                continue;

            var categoryButton = new CategoryButton(category, GetLocalizedName(category.Prototype));
            categoryButton.OnPressed += _ => GoIntoCategory(category);
            Model.TabContainer.AddChild(categoryButton);
        }
    }

    protected virtual void UpdateChoices()
    {
        Model.ChoicesContainer.RemoveAllChildren();

        var currentCategory = CurrentPath.Count > 0
            ? CurrentPath.Peek().Prototypes
            : null;

        if (currentCategory == null)
        {
            Model.ChoicesContainer.AddChild(new Label()
            {
                Text = "This category contains no items." // TODO localize
            });
            return;
        }

        foreach (var prototype in currentCategory)
        {
            if (!ShowUnusable && !IsUsable(prototype, out var reasons))
                continue;

            var selector = CreateSelector(prototype);
            Model.ChoicesContainer.AddChild(selector);
        }

        if (Model.ChoicesContainer.ChildCount == 0)
        {
            Model.ChoicesContainer.AddChild(new Label()
            {
                Text = "No items match the requirements." // TODO localize
            });
        }
    }

    protected virtual void UpdateDetails()
    {
        if (ShowingDetailsFor == null)
        {
            Model.DetailsContainer.Visible = false;
            return;
        }

        Model.DetailsContainer.Visible = true;
        Model.DetailsContainer.RemoveAllChildren();
        UpdateExtendedPanel();
    }

    protected virtual void RemoveUnusable()
    {
        var unset = 0;
        foreach (var prototype in AllPrototypes)
        {
            if (!IsSelected(prototype) || IsUsable(prototype, out var reasons))
                continue;

            SetSelected(prototype, false);
            unset++;
        }

        Log.Info($"Deselected {unset} items.");
    }

    /// <summary>
    ///     Should be called by inheritors when/if the user wants to expand the given item.
    /// </summary>
    public void Expand(TProto? prototype)
    {
        ShowingDetailsFor = prototype;
        UpdateDetails();
    }

    /// <summary>
    ///     Appends a category to the current path. Does not validate the resulting path.
    /// </summary>
    /// <param name="category"></param>
    public void GoIntoCategory(CategoryTreeItem category)
    {
        if (category.Prototype == null)
            return;

        ShowingDetailsFor = null;
        CurrentPath.Push(category);
        UpdateAll();
    }

    /// <summary>
    ///     Returns to the given category depth in the path. If depth is 1 or less, returns to the root.
    /// </summary>
    public void GoBackTo(int depth)
    {
        EnsurePathIsRooted();

        ShowingDetailsFor = null;
        while (CurrentPath.Count > depth)
            CurrentPath.Pop();

        UpdateAll();
    }

    public void UpdateAll()
    {
        UpdatePath();
        UpdateCategories();
        UpdateChoices();
        UpdateDetails();
        UpdateCounters();
    }

    public abstract TSelector CreateSelector(TProto prototype);

    /// <summary>
    ///     Called when the user tries to view the extended detail/settings of a prototype.
    ///     Should update DetailsContainer (note that it will usually be cleared - though not disposed of - before calling this).
    /// </summary>
    protected abstract void UpdateExtendedPanel();

    /// <summary>
    ///     Checks if the player can use the provided loadout, regardless of points.
    /// </summary>
    public abstract bool IsUsable(TProto prototype, out List<string> reasons);

    public abstract bool IsSelected(TProto prototype);

    public abstract void SetSelected(TProto prototype, bool selected);

    public abstract string GetLocalizedName(TCategory prototype);

    public abstract string GetLocalizedName(TProto prototype);

    public record class PointCounterDef(string locString, Func<TProto, int> GetPrototypePoints, Func<int> GetMaxPoints)
    {
        public int CurrentPoints { get; internal set; } = int.MinValue;
        public int MaxPoints { get; internal set; } = int.MinValue;

        public bool Valid =>
            MaxPoints != int.MinValue
            && CurrentPoints != int.MinValue
            && (CurrentPoints >= 0 || MaxPoints == int.MaxValue);

        internal PointCounterControl? Control;
    }

    /// <summary>
    ///     An item of the prototype tree. It can either be terminal and contain prototypes, or be non-terminal and contain subcategories.
    ///     It cannot be both. The category field can only be null for the root category.
    /// </summary>
    public record class CategoryTreeItem(TCategory? Prototype, string LocalizedName, List<TProto>? Prototypes, List<CategoryTreeItem>? Subcategories)
    {
        public bool Terminal => Prototypes != null;
        public bool NonTerminal => Subcategories != null;

        public void Validate()
        {
            if (Terminal && NonTerminal)
                throw new InvalidOperationException($"Prototype {typeof(TCategory).Name} {Prototype?.ID} must contain either prototypes or subcategories, but not both.");
        }
    }

    public sealed class PathButton : Button
    {
        public TCategory? Category { get; }
        public string LocalizedName { get; }
        public int Depth { get; }

        public readonly TextureRect Image;

        public PathButton(TCategory? category, string localizedName, int depth)
        {
            Category = category;
            LocalizedName = localizedName;
            Depth = depth;

            HorizontalAlignment = HAlignment.Stretch;

            var isRoot = category == null;
            // Root category is represented by a home sign. Non-root ones are an arrow + text
            if (isRoot)
            {
                Text = null;
                Image = new()
                {
                    TexturePath = "/Textures/Interface/home.png",
                    SetSize = new(20),
                    HorizontalAlignment = HAlignment.Left,
                };
                AddChild(Image);
            }
            else
            {
                Text = localizedName;
                Image = new()
                {
                    TexturePath = "/Textures/Interface/AdminActions/play.png", // Play button looks like an arrow
                    SetSize = new(20),
                    HorizontalAlignment = HAlignment.Left,
                };
                AddChild(Image);
            }
        }
    }

    public sealed class CategoryButton : Button
    {
        public CategoryTreeItem Category { get; }
        public string LocalizedName { get; }

        public CategoryButton(CategoryTreeItem category, string localizedName)
        {
            Category = category;
            LocalizedName = localizedName;

            Text = localizedName;
            StyleClasses.Add("OpenBoth");
        }
    }
}
