using System.Linq;
using Content.Client.Guidebook;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Content.Shared.Paint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;


namespace Content.Client._Floof.LoadoutsAndTraits;


[GenerateTypedNameReferences]
public sealed partial class LoadoutSelector2 : Control
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly ILocalizationManager _locMan = default!;

    private readonly LoadoutTreeCharacterPage _parent;
    public LoadoutPreference Preference;
    public LoadoutPrototype Prototype;
    public EntityUid? DummyEntity { get; private set; }

    public LoadoutSelector2(LoadoutTreeCharacterPage parent, LoadoutPreference preference, LoadoutPrototype proto)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _parent = parent;
        Preference = preference;
        Prototype = proto;

        UpdateFromPreference();
        if (Prototype.Items.Count == 0)
            DummyEntity = EntityUid.Invalid; // I don't care, just nuke it

        LoadoutCost.StyleClasses.Add(StyleBase.StyleClassLabelHeading);
        PreferenceButton.StyleClasses.Add(ContainerButton.StyleClassButton);

        PreferenceButton.OnPressed += _ =>
        {
            Preference.Selected = !Preference.Selected;
            _parent.Dirty();
            _parent.UpdateChoices(); // This may invalidate other options due to loadout groups
            _parent.UpdateCounters();
        };
        HeirloomButton.OnPressed += _ =>
        {
            Preference.CustomHeirloom = Preference.CustomHeirloom != true; // {false,null} -> true, true -> false
            _parent.Dirty();
            _parent.UpdateCounters();
        };
        GuidebookButton.OnPressed += _ => OpenGuidebook();
        SettingsButton.OnPressed += _ => parent.Expand(Prototype);
    }

    ~LoadoutSelector2()
    {
        // Suuurely this is safe, right?
        _entMan.QueueDeleteEntity(DummyEntity);
        DummyEntity = null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (Visible && DummyEntity == null)
            InitializeEntity();
    }

    private void InitializeEntity()
    {
        try { DummyEntity = _entMan.Spawn(Prototype.Items.First()); }
        catch (Exception e)
        {
            Logger.Error($"Failed to spawn dummy entity for loadout {Preference.LoadoutName}", e);
            try { DummyEntity = _entMan.Spawn("Error"); }
            catch (Exception e2) { Logger.Error($"Error entity failed too?", e2); }

            return;
        }

        UpdateFromPreference(); // So we set up paint
        EntPreview.SetEntity(DummyEntity);
    }

    private void UpdateFromPreference()
    {
        if (!Prototype.CustomName)
            Preference.CustomName = null;
        if (!Prototype.CustomDescription)
            Preference.CustomDescription = null;
        if (!Prototype.CustomColorTint)
            Preference.CustomColorTint = null;
        if (!Prototype.CanBeHeirloom)
            Preference.CustomHeirloom = false;

        LoadoutCost.Text = $"{Prototype.Cost}";
        LoadoutLocName.Text = Preference.CustomName ?? LocOrDefaultName($"loadout-name-{Prototype.ID}");
        PreferenceButton.Pressed = Preference.Selected;
        HeirloomButton.Pressed = Preference.CustomHeirloom == true;

        HeirloomButton.Visible = Prototype.CanBeHeirloom;
        GuidebookButton.Visible = !string.IsNullOrEmpty(Prototype.GuideEntry);

        if (DummyEntity == null)
            return;

        if (Preference.CustomColorTint != null && Color.TryParse(Preference.CustomColorTint, out var tintColor))
        {
            var app = _entMan.EnsureComponent<AppearanceComponent>(DummyEntity.Value);
            var paint = _entMan.EnsureComponent<PaintedComponent>(DummyEntity.Value);
            paint.Color = tintColor;
            paint.Enabled = true;
            _entMan.System<SharedAppearanceSystem>().SetData(DummyEntity.Value, PaintVisuals.Painted, true, app);
        }
        else
            _entMan.RemoveComponent<PaintedComponent>(DummyEntity.Value);
    }

    private string LocOrDefaultName(string loc)
    {
        if (_locMan.TryGetString(loc, out var customDesc))
            return customDesc;
        if (_entMan.TryGetComponent<MetaDataComponent>(DummyEntity, out var meta))
            return meta.EntityName;
        return "???";
    }

    public void OpenGuidebook()
    {
        if (!_protoMan.TryIndex<GuideEntryPrototype>(Prototype.GuideEntry, out var guideRoot))
            return;

        var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
        guidebookController.ToggleGuidebook(
            new Dictionary<string, GuideEntry> { { Prototype.GuideEntry, guideRoot } },
            includeChildren: true,
            selected: Prototype.GuideEntry);
    }
}
